// Automatically generated by flapigen
#pragma once

struct C_DataObserver {
    void *opaque;
    //! call by Rust side when callback not need anymore
    void (*C_DataObserver_deref)(void *opaque);

    void (*onData)(struct CRustString result, void *opaque);

    void (*onError)(struct CRustString result, void *opaque);

};
