// Automatically generated by flapigen

#pragma once

//for (u)intX_t types
#include <stdint.h>

#ifdef __cplusplus
static_assert(sizeof(uintptr_t) == sizeof(uint8_t) * 4,
   "our conversation usize <-> uintptr_t is wrong");
extern "C" {
#endif

    typedef struct HiddenServiceHandlerOpaque HiddenServiceHandlerOpaque;


    HiddenServiceHandlerOpaque *HiddenServiceHandler_new(uint16_t dst_port, const struct C_DataObserver * const cb);

    void HiddenServiceHandler_delete(const HiddenServiceHandlerOpaque *self);

#ifdef __cplusplus
}
#endif

