// Automatically generated by flapigen

#pragma once

//for (u)intX_t types
#include <stdint.h>

#ifdef __cplusplus
static_assert(sizeof(uintptr_t) == sizeof(uint8_t) * 4,
   "our conversation usize <-> uintptr_t is wrong");
extern "C" {
#endif

    typedef struct LoggerOpaque LoggerOpaque;


    LoggerOpaque * Logger_new();

    void Logger_delete(const LoggerOpaque *self);

#ifdef __cplusplus
}
#endif

