// Automatically generated by flapigen

#pragma once

//for (u)intX_t types
#include <stdint.h>

#ifdef __cplusplus
static_assert(sizeof(uintptr_t) == sizeof(uint8_t) * 4,
   "our conversation usize <-> uintptr_t is wrong");
extern "C" {
#endif

    typedef struct OwnedTorServiceOpaque OwnedTorServiceOpaque;


    OwnedTorServiceOpaque *OwnedTorService_new(TorServiceParamOpaque * param);

    uint16_t OwnedTorService_getSocksPort(const OwnedTorServiceOpaque * const self);

    struct CRustVoidOkResultCRustString OwnedTorService_shutdown(OwnedTorServiceOpaque * const self);

    struct CRustString OwnedTorService_get_status(OwnedTorServiceOpaque * const self);

    struct CRustResult4232mut3232c_voidCRustString OwnedTorService_create_hidden_service(OwnedTorServiceOpaque * const self, uint16_t dst_port, uint16_t hs_port, struct CRustStrView secret_key);

    struct CRustVoidOkResultCRustString OwnedTorService_delete_hidden_service(OwnedTorServiceOpaque * const self, struct CRustStrView onion);

    void OwnedTorService_delete(const OwnedTorServiceOpaque *self);

#ifdef __cplusplus
}
#endif

