// Automatically generated by flapigen

#pragma once

//for (u)intX_t types
#include <stdint.h>

#ifdef __cplusplus
static_assert(sizeof(uintptr_t) == sizeof(uint8_t) * 4,
   "our conversation usize <-> uintptr_t is wrong");
extern "C" {
#endif

    typedef struct TcpSocksStreamOpaque TcpSocksStreamOpaque;


    TcpSocksStreamOpaque *TcpSocksStream_new(struct CRustStrView target, struct CRustStrView socks_proxy, uint64_t timeout_ms);

    struct CRustVoidOkResultCRustString TcpSocksStream_on_data(TcpSocksStreamOpaque * const self, const struct C_DataObserver * const cb);

    struct CRustVoidOkResultCRustString TcpSocksStream_send_data(TcpSocksStreamOpaque * const self, struct CRustStrView msg, uint64_t timeout);

    void TcpSocksStream_delete(const TcpSocksStreamOpaque *self);

#ifdef __cplusplus
}
#endif

