// Automatically generated by flapigen

#pragma once

//for (u)intX_t types
#include <stdint.h>

#ifdef __cplusplus
static_assert(sizeof(uintptr_t) == sizeof(uint8_t) * 4,
   "our conversation usize <-> uintptr_t is wrong");
extern "C" {
#endif

    typedef struct TorServiceParamOpaque TorServiceParamOpaque;


    TorServiceParamOpaque *TorServiceParam_new(struct CRustStrView data_dir, uint16_t socks_port, uint64_t bootstap_timeout_ms);

    void TorServiceParam_delete(const TorServiceParamOpaque *self);

#ifdef __cplusplus
}
#endif

