// Automatically generated by flapigen

#pragma once

//for (u)intX_t types
#include <stdint.h>

#ifdef __cplusplus
static_assert(sizeof(uintptr_t) == sizeof(uint8_t) * 4,
   "our conversation usize <-> uintptr_t is wrong");
extern "C" {
#endif

    typedef struct TorHiddenServiceOpaque TorHiddenServiceOpaque;


    struct CRustString TorHiddenService_get_onion_url(const TorHiddenServiceOpaque * const self);

    struct CRustString TorHiddenService_get_secret_b64(const TorHiddenServiceOpaque * const self);

    void TorHiddenService_delete(const TorHiddenServiceOpaque *self);

#ifdef __cplusplus
}
#endif

