// Automatically generated by flapigen
#pragma once

namespace sifir_lib {
template<bool>
class HiddenServiceHandlerWrapper;
using HiddenServiceHandler = HiddenServiceHandlerWrapper<true>;
using HiddenServiceHandlerRef = HiddenServiceHandlerWrapper<false>;
} // namespace sifir_lib
