// Automatically generated by flapigen
#pragma once

namespace sifir_lib {
template<bool>
class LoggerWrapper;
using Logger = LoggerWrapper<true>;
using LoggerRef = LoggerWrapper<false>;
} // namespace sifir_lib
