// Automatically generated by flapigen
#pragma once

namespace sifir_lib {
template<bool>
class OwnedTorServiceWrapper;
using OwnedTorService = OwnedTorServiceWrapper<true>;
using OwnedTorServiceRef = OwnedTorServiceWrapper<false>;
} // namespace sifir_lib
