// Automatically generated by flapigen
#pragma once

//for (u)intX_t types
#include <stdint.h>

#ifdef __cplusplus
static_assert(sizeof(uintptr_t) == sizeof(uint8_t) * 4,
   "our conversation usize <-> uintptr_t is wrong");
#endif
            #include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif
struct CRustObjectSlice {
    /*const*/void * data;
    uintptr_t len;
    uintptr_t step;
};

#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
#include "rust_foreign_slice_impl.hpp"

namespace sifir_lib {
template<typename T>
using RustForeignSliceConst = RustForeignSlice<T, CRustObjectSlice>;
}
#endif
