// Automatically generated by flapigen
#pragma once

//for (u)intX_t types
#include <stdint.h>

#ifdef __cplusplus
static_assert(sizeof(uintptr_t) == sizeof(uint8_t) * 4,
   "our conversation usize <-> uintptr_t is wrong");
#endif
            #include "rust_str.h"

#ifdef __cplusplus
extern "C" {
#endif
union CRustResultUnion4232mut3232c_voidCRustString {
    void * ok;
    struct CRustString err;
};

#ifdef __cplusplus
} // extern "C" {
#endif
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif
struct CRustResult4232mut3232c_voidCRustString {
    union CRustResultUnion4232mut3232c_voidCRustString data;
    uint8_t is_ok;
};

#ifdef __cplusplus
} // extern "C" {
#endif
