// Automatically generated by flapigen
#pragma once

//for (u)intX_t types
#include <stdint.h>

#ifdef __cplusplus
static_assert(sizeof(uintptr_t) == sizeof(uint8_t) * 4,
   "our conversation usize <-> uintptr_t is wrong");
#endif
            #include <stdint.h>
#include "rust_str.h"

#ifdef __cplusplus
extern "C" {
#endif
union CRustVoidOkResultUnionCRustString {
    uint8_t ok;
    struct CRustString err;
};

#ifdef __cplusplus
} // extern "C" {
#endif
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif
struct CRustVoidOkResultCRustString {
    union CRustVoidOkResultUnionCRustString data;
    uint8_t is_ok;
};

#ifdef __cplusplus
} // extern "C" {
#endif
