// Automatically generated by flapigen
#pragma once

//for (u)intX_t types
#include <stdint.h>

#ifdef __cplusplus
static_assert(sizeof(uintptr_t) == sizeof(uint8_t) * 4,
   "our conversation usize <-> uintptr_t is wrong");
#endif
            #include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif
struct CRustForeignVec {
    /*const*/void * data;
    uintptr_t len;
    uintptr_t capacity;
    uintptr_t step;
};

#ifdef __cplusplus
} // extern "C" {
#endif
