// Automatically generated by flapigen
#pragma once

namespace sifir_lib {
template<bool>
class TcpSocksStreamWrapper;
using TcpSocksStream = TcpSocksStreamWrapper<true>;
using TcpSocksStreamRef = TcpSocksStreamWrapper<false>;
} // namespace sifir_lib
