// Automatically generated by flapigen
#pragma once

namespace sifir_lib {
template<bool>
class TorHiddenServiceWrapper;
using TorHiddenService = TorHiddenServiceWrapper<true>;
using TorHiddenServiceRef = TorHiddenServiceWrapper<false>;
} // namespace sifir_lib
