// Automatically generated by flapigen
#pragma once

namespace sifir_lib {
template<bool>
class TorServiceParamWrapper;
using TorServiceParam = TorServiceParamWrapper<true>;
using TorServiceParamRef = TorServiceParamWrapper<false>;
} // namespace sifir_lib
